import React, { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { addItem } from './CartSlice';
import CartItem from './CartItem';

const plantsArray = [
  {
      category: "Air Purifying Plants",
          plants: [
                { name: "Snake Plant", image: "https://cdn.pixabay.com/photo/2021/01/22/06/04/snake-plant-5939187_1280.jpg", cost: "$15" },
                      { name: "Spider Plant", image: "https://cdn.pixabay.com/photo/2018/07/11/06/47/chlorophytum-3530413_1280.jpg", cost: "$12" },
                            { name: "Peace Lily", image: "https://cdn.pixabay.com/photo/2019/06/12/14/14/peace-lily-4269365_1280.jpg", cost: "$18" },
                                  { name: "Boston Fern", image: "https://cdn.pixabay.com/photo/2020/04/30/19/52/boston-fern-5114414_1280.jpg", cost: "$14" },
                                        { name: "Rubber Plant", image: "https://cdn.pixabay.com/photo/2020/02/15/11/49/flower-4850729_1280.jpg", cost: "$20" },
                                              { name: "Aloe Vera", image: "https://cdn.pixabay.com/photo/2018/04/05/14/09/aloe-vera-3292941_1280.jpg", cost: "$10" }
                                                  ]
                                                    },
                                                      {
                                                          category: "Aromatic Fragrant Plants",
                                                              plants: [
                                                                    { name: "Lavender", image: "https://cdn.pixabay.com/photo/2015/07/02/10/22/lavender-828911_1280.jpg", cost: "$20" },
                                                                          { name: "Jasmine", image: "https://cdn.pixabay.com/photo/2017/08/07/14/02/jasmine-2604100_1280.jpg", cost: "$18" },
                                                                                { name: "Rosemary", image: "https://cdn.pixabay.com/photo/2019/10/11/07/12/rosemary-4541241_1280.jpg", cost: "$15" },
                                                                                      { name: "Mint", image: "https://cdn.pixabay.com/photo/2016/01/07/12/03/mint-1125810_1280.jpg", cost: "$10" },
                                                                                            { name: "Lemon Balm", image: "https://cdn.pixabay.com/photo/2017/05/18/17/30/lemon-balm-2324180_1280.jpg", cost: "$12" },
                                                                                                  { name: "Hyacinth", image: "https://cdn.pixabay.com/photo/2019/04/07/18/08/hyacinth-4110332_1280.jpg", cost: "$22" }
                                                                                                      ]
                                                                                                        },
                                                                                                          {
                                                                                                              category: "Low Maintenance Plants",
                                                                                                                  plants: [
                                                                                                                        { name: "ZZ Plant", image: "https://cdn.pixabay.com/photo/2021/01/06/09/16/zz-plant-5893696_1280.jpg", cost: "$25" },
                                                                                                                              { name: "Pothos", image: "https://cdn.pixabay.com/photo/2018/11/15/10/32/pothos-3816943_1280.jpg", cost: "$12" },
                                                                                                                                    { name: "Cast Iron Plant", image: "https://cdn.pixabay.com/photo/2020/05/17/12/38/plant-5181463_1280.jpg", cost: "$20" },
                                                                                                                                          { name: "Jade Plant", image: "https://cdn.pixabay.com/photo/2016/11/21/16/08/succulent-1846151_1280.jpg", cost: "$15" },
                                                                                                                                                { name: "Succulent", image: "https://cdn.pixabay.com/photo/2016/11/19/15/32/succulents-1839886_1280.jpg", cost: "$10" },
                                                                                                                                                      { name: "Chinese Evergreen", image: "https://cdn.pixabay.com/photo/2020/12/09/16/03/aglaonema-5817882_1280.jpg", cost: "$18" }
                                                                                                                                                          ]
                                                                                                                                                            }
                                                                                                                                                            ];

                                                                                                                                                            function ProductList() {
                                                                                                                                                              const [showCart, setShowCart] = useState(false);
                                                                                                                                                                const [addedToCart, setAddedToCart] = useState({});
                                                                                                                                                                  const dispatch = useDispatch();
                                                                                                                                                                    const cartItems = useSelector(state => state.cart.items);

                                                                                                                                                                      const totalCartCount = cartItems.reduce((total, item) => total + item.quantity, 0);

                                                                                                                                                                        const handleAddToCart = (plant) => {
                                                                                                                                                                            dispatch(addItem(plant));
                                                                                                                                                                                setAddedToCart((prevState) => ({
                                                                                                                                                                                      ...prevState,
                                                                                                                                                                                            [plant.name]: true,
                                                                                                                                                                                                }));
                                                                                                                                                                                                  };

                                                                                                                                                                                                    const handleCartClick = (e) => {
                                                                                                                                                                                                        e.preventDefault();
                                                                                                                                                                                                            setShowCart(true);
                                                                                                                                                                                                              };

                                                                                                                                                                                                                const handleContinueShopping = (e) => {
                                                                                                                                                                                                                    if (e) e.preventDefault();
                                                                                                                                                                                                                        setShowCart(false);
                                                                                                                                                                                                                          };

                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                      {/* Navbar */}
                                                                                                                                                                                                                                            <nav className="navbar" style={{ display: 'flex', justifyContent: 'space-between', padding: '15px 30px', backgroundColor: '#4CAF50', color: 'white', alignItems: 'center' }}>
                                                                                                                                                                                                                                                    <h2>Paradise Nursery</h2>
                                                                                                                                                                                                                                                            <div style={{ display: 'flex', gap: '20px', alignItems: 'center' }}>
                                                                                                                                                                                                                                                                      <a href="#" onClick={() => setShowCart(false)} style={{ color: 'white', textDecoration: 'none' }}>Home</a>
                                                                                                                                                                                                                                                                                <a href="#" onClick={() => setShowCart(false)} style={{ color: 'white', textDecoration: 'none' }}>Plants</a>
                                                                                                                                                                                                                                                                                          <a href="#" onClick={handleCartClick} style={{ color: 'white', textDecoration: 'none', position: 'relative' }}>
                                                                                                                                                                                                                                                                                                      🛒 Cart <span style={{ backgroundColor: 'red', borderRadius: '50%', padding: '2px 8px', fontSize: '12px' }}>{totalCartCount}</span>
                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                              </nav>

                                                                                                                                                                                                                                                                                                                                    {!showCart ? (
                                                                                                                                                                                                                                                                                                                                            <div style={{ padding: '20px' }}>
                                                                                                                                                                                                                                                                                                                                                      {plantsArray.map((categoryObj, index) => (
                                                                                                                                                                                                                                                                                                                                                                  <div key={index} style={{ marginBottom: '40px' }}>
                                                                                                                                                                                                                                                                                                                                                                                <h2 style={{ textAlign: 'center', borderBottom: '2px solid #4CAF50', paddingBottom: '10px' }}>{categoryObj.category}</h2>
                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '20px', justifyContent: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                              {categoryObj.plants.map((plant, pIndex) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                <div key={pIndex} style={{ border: '1px solid #ccc', borderRadius: '8px', padding: '15px', width: '220px', textAlign: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <img src={plant.image} alt={plant.name} style={{ width: '100%', height: '180px', objectFit: 'cover', borderRadius: '6px' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3>{plant.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>{plant.cost}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => handleAddToCart(plant)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            disabled={addedToCart[plant.name] || cartItems.some(item => item.name === plant.name)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{ padding: '8px 16px', backgroundColor: (addedToCart[plant.name] || cartItems.some(item => item.name === plant.name)) ? '#ccc' : '#4CAF50', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {(addedToCart[plant.name] || cartItems.some(item => item.name === plant.name)) ? "Added to Cart" : "Add to Cart"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <CartItem onContinueShopping={handleContinueShopping} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default ProductList;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        